### ISSUE TITLE
Fully Rewrite Krist

### ISSUE THREAD

**Issue by dmarcuse** [KristFoundation/KristClassA#2]
Seeing how large Krist has become, I think it is clear that the framework behind it works, but the server issues (slow transaction loading, etc) are becoming apparent. I feel that we should start a _full rewrite_ of Krist at some point - server as well as client.

One major issue right now is speed. One cause is the way API calls are handled. There should be hard limits on how many transactions are returned per request, for example.

Another issue that will soon become more prevalent I believe is security. With only a single password, which is just a lot of repetitive hashes, it is probably more profitable to mine for _addresses_ than blocks - especially with the value of blocks dropping. I believe Krist addresses v3 should require a username and password.

Finally, the way data is provided from the API (concatenated strings) is difficult to use, and inefficient. I feel that switching to JSON, XML, or CSV would encourage new Krist-based applications. For compatibility reasons, we could also write it in such a way that using a GET parameter such as "?format=xml" can be used to specify which format you would like data to be returned in.

**Comment by BTCTaras** [comment]
I agree completely that everything should be rewritten before or after going P2P. We should also want to add hooks (as suggested around page 2 of the thread) and maybe move everything.

I have a few candidates for inclusion in the Krist Foundation; they may have more ideas.

Honestly I'm not really sure where to start on this. I was working on KristScape and KristWallet 12 with valithor et al, got busy with school, graduated, and am now working on reviving my old vanilla network. I haven't done anything Krist-related for a week; and in that time period I solved one block.

**Comment by BTCTaras** [comment]
Just uploaded the latest code used in Krist, with domains etc.

There are some things in there completely unrelated to the project - including me screwing with Lur and Medders, in May and February, respectively

I probably should have removed those bits before uploading

**Comment by Lemmmy** [comment]
I'm on it
